#pragma config(Motor,  port2,           rightMotor,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           leftMotor,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           armMotor,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           clawMotor,     tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*

	Port2 - left hand drive motor
	Port3 - right hand drive motor
	Port4 - arm up and down
	Prot5 - claw motor

*/

void control() {

	int HORRIZONTAL_AXIS = 0;
	int VERTICAL_AXIS = 1;

	//Get the data
	int leftStick[] = {vexRT[Ch4], vexRT[Ch3]};
	int rightStick[] = {vexRT[Ch1], vexRT[Ch2]};

	motor[leftMotor] = leftStick[VERTICAL_AXIS];
	motor[rightMotor] = rightStick[VERTICAL_AXIS];

	//motor[armMotor] = leftStick[HORRIZONTAL_AXIS];
	//motor[clawMotor] = rightStick[HORRIZONTAL_AXIS];
	motor[armMotor] = (vexRT[Btn5D] - vexRT[Btn5U]) * 127;
	motor[clawMotor] = (vexRT[Btn6D] - vexRT[Btn6U]) * 127;
}

task main()
{

	int a =0;

	while (true) {

		a = a +1;

		//motor[leftMotor] = 100;
		control();

	}

}
